# Generated by Django 4.2.1 on 2023-05-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='make')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('year', models.IntegerField(verbose_name='year')),
            ],
            options={
                'verbose_name': 'carmodel',
                'verbose_name_plural': 'carmodels',
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_nr', models.CharField(max_length=20, verbose_name='car_nr')),
                ('vin', models.CharField(max_length=50, verbose_name='vin')),
                ('client', models.CharField(max_length=50, verbose_name='client')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_service.carmodel', verbose_name='carmodel')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'ordering': ['car_nr', 'car_model', 'client'],
            },
        ),
    ]
