# Generated by Django 4.2.1 on 2023-05-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0002_order_service_order_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'Waiting'), (1, 'In progress'), (2, 'Finished'), (3, 'Ready for pick up'), (7, 'Not fixable')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
