# Generated by Django 4.2.1 on 2023-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='car_service/car_covers', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
