# Generated by Django 4.2.1 on 2023-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0004_order_cover_alter_order_info_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cover',
        ),
        migrations.AddField(
            model_name='car',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='car_service/car_covers', verbose_name='cover'),
        ),
    ]
