# Generated by Django 4.2.1 on 2023-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0006_car_reader_order_due_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='reader',
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='client'),
        ),
    ]
