# Generated by Django 4.2.1 on 2023-06-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0007_remove_car_reader_alter_car_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_nr', 'car_model'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='client',
        ),
    ]
