# Generated by Django 4.2.1 on 2023-06-08 15:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0012_alter_car_car_nr_alter_order_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='car_description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, max_length=8000, null=True, verbose_name='order_summary'),
        ),
    ]
