# Generated by Django 4.2.1 on 2023-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0013_alter_car_description_alter_order_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='cost'),
        ),
    ]
